---
- name: Install CDM certificates
  ansible.builtin.include_role:
    name: cdm_certificates
  vars:
    cdm_certificates_third_party_bucket_name: "{{ cdm_nessus_agent_third_party_bucket_name }}"

- name: Load var file with package names based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

# Check if Nessus Agent is already installed
- name: Check if Nessus Agent is already installed
  ansible.builtin.stat:
    path: "{{ cdm_nessus_agent_install_directory }}"
  register: nessus_directory

- name: Install Nessus Agent
  when: not nessus_directory.stat.exists
  block:
    - name: Grab Nessus Agent system package from S3
      amazon.aws.aws_s3:
        bucket: "{{ cdm_nessus_agent_third_party_bucket_name }}"
        object: "{{ package_object_name }}"
        dest: /tmp/{{ package_object_name }}
        mode: get
      become: no
      delegate_to: localhost

    - name: Copy the Nessus Agent system package
      ansible.builtin.copy:
        dest: /tmp/{{ package_object_name }}
        mode: 0700
        src: /tmp/{{ package_object_name }}

    - name: Load tasks file based on the OS type
      ansible.builtin.include_tasks: "{{ lookup('first_found', params) }}"
      vars:
        params:
          files:
            - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
            - "{{ ansible_distribution }}.yml"
            - "{{ ansible_os_family }}.yml"
          paths:
            - "{{ role_path }}/tasks"

    - name: Enable the Nessus Agent service
      ansible.builtin.service:
        enabled: yes
        name: nessusagent
        # Required to set the update_hostname option below
        state: started

    - name: Configure the Nessus Agent to send hostname updates
      ansible.builtin.command:
        argv:
          - "{{ cdm_nessus_agent_install_directory }}/sbin/nessuscli"
          - fix
          - --set
          - update_hostname=yes
      changed_when: nessuscli_output.rc == 0
      failed_when: nessuscli_output.rc != 0
      register: nessuscli_output

    - name: Delete local copy of Nessus Agent system package
      ansible.builtin.file:
        path: /tmp/{{ package_object_name }}
        state: absent
      become: no
      delegate_to: localhost

    - name: Delete remote copy of Nessus Agent system package
      ansible.builtin.file:
        path: /tmp/{{ package_object_name }}
        state: absent
