---
- name: Grab Nessus Agent system package GPG key from S3
  ansible.builtin.aws_s3:
    bucket: "{{ cdm_nessus_agent_third_party_bucket_name }}"
    object: "{{ package_gpg_key_object_name }}"
    dest: /tmp/{{ package_gpg_key_object_name }}
    mode: get
  become: no
  delegate_to: localhost

- name: Copy the Nessus Agent system package GPG key
  ansible.builtin.copy:
    dest: /tmp/{{ package_gpg_key_object_name }}
    mode: 0700
    src: /tmp/{{ package_gpg_key_object_name }}

- name: Import Nessus Agent system package GPG key
  ansible.builtin.rpm_key:
    key: /tmp/{{ package_gpg_key_object_name }}

- name: Install Nessus Agent (RedHat)
  ansible.builtin.yum:
    name:
      - /tmp/{{ package_object_name }}

- name: Delete local copy of Nessus Agent system package GPG key
  ansible.builtin.file:
    path: /tmp/{{ package_gpg_key_object_name }}
    state: absent
  become: no
  delegate_to: localhost

- name: Delete remote copy of Nessus Agent system package GPG key
  ansible.builtin.file:
    path: /tmp/{{ package_gpg_key_object_name }}
    state: absent
